;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	er/mark-inside-pairs
	er/mark-outside-pairs
	modal/backward-char
	modal/backward-word
	modal/beginning-of-line-or-paragraph
	modal/end-of-line-or-paragraph
	modal/extend-selection-backward-word
	modal/extend-selection-forward-word
	modal/forward-char
	modal/forward-word
	modal/next-line
	modal/previous-line
	modal/start
	paredit-RET
	transpose-words
	))

(setq mc/cmds-to-run-once
      '(
	mc/mark-next-lines
	))
